language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"

env:
  global:
  - secure: "bDam3dS27j8trLOV0xIXJjwZ51ber7OtRO/emFMg877a+2tatwxAiAJ24OobJQQYQ+BXZBbcYw2Lm4tzOYPlwOZMLgnnddwU36tMhUmv5QCmVk4/ftUEZHRtewcZ17ks0//KODS1Pzx9IBwztyRkUSIlNQvUrSyf31WY2FnjTnCdMxk0dKxJtKXUTcSZTf6wIuT6kLhwILXHjMThKesZ1G9P2MaDbg8CMauYonFXCKSfp2Mx3Ee4qTZIoPgJRiwbvNQ/B5Co8JrqbGBRblRN+FKJz1V1Szqz3sCboKCUf06ZxVuOF1gmOedacEvt4V3fF62svJI7tEvPNbhi7qVQnQk6BYe+J0LdN2cuuOJbBPiQAhZUcwVIxOGkbOpcYoAa0kZA+AGugiNRyqAP1vpf+GPSZqedabXP4F+tZ3oE1iNnCHhsJe1U6Rb602R888h4cEsCU9gikMNo5uigPNo95IaNbNrHk/PFbXefR4kgdWukkE5alwlV5gOd8AB4HT0C7kw5MGaPjsBeWyyPPgNCp48pktdqW20fM4y1Mo5lEFJv56h31qVJBX0B0e1SFiNh5YMpX1WTlvJp8hKv4K/Uianmja/uZbk6MkmY9f1vX+r6lFGtYlhqNZACov91nz303Yur9WoYmHrUgi1BIFC6AEDVcHwsoctvZt+sRA56ens="

before_install:
- npm install -g jspm
- jspm config registries.github.auth $JSPM_GITHUB_AUTH_TOKEN
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- export CHROME_BIN=chromium-browser
- jspm install --dev
